Dimos christidis
OldDognoob/JavaScript-I pull request #1
Opened 2019-10-14 15:02 UTC by OldDognoob

1. Functions-conventions
2.Objects
3.Arrays
The project needs some revision to be complete.

2019-10-15 09:24 UTC, Becheru888 requested changes
Dimos you were close! 💯 

I can see that you understood how an object literal is created. You know how to call an object property and console.log it 👍  
The challenge no 3 from the objects is not going to work because you must add your method 
` const kennanspeak = function () {
    return("Hello, my name is Kennan!");
  }` inside Kennan's object. And then you call it with `objectName.objectMethod() ` 
Similar thing applies to Antonietta 👍  

From the array please review the challenge no 1 and challenge 2, and use the `for loop` from examples.

Try to not leave empty console logs into your code.

You still have few things to complete but looks like you have a good understanding of `for loop` and `objects`.

Keep pushing 💯

2019-12-17 16:44 UTC, haywhyze approved these changes

2019-12-17 16:44 UTC, haywhyze commented on assignments/function-conversion.js
> +  let anotherFunction=(param)=>{return param;};
you can also exclude the return statement and the curly braces if the arrow function is a one liner

2019-12-17 16:45 UTC, haywhyze commented
Good work on this Dimos!!!

2019-12-17 16:45 UTC, merged